html-basics
TrandafilTatiana/Tekwill_FE_gr14 pull request #2
Opened 2024-12-19 14:40 UTC by TrandafilTatiana

<img width="575" alt="Screen Shot 2024-12-19 at 4 25 44 PM" src="https://github.com/user-attachments/assets/5767a0b9-3c53-409d-9080-89090fe98bd0" />

2024-12-19 14:51 UTC, IvanCeban requested changes
Great job!
Just 1 small improvement required

2024-12-19 15:30 UTC, TrandafilTatiana commented on index.html
> +      >ext <b>M</b>arkup <strong>L</strong>anguage. It's a markup language that
Ok. I just wanted to show all cases)

2024-12-19 15:41 UTC, IvanCebanPVT approved these changes
Wrong account, sorry

2024-12-19 21:15 UTC, ciocoialexandru commented
Looks awesome!

2024-12-19 21:16 UTC, ciocoialexandru approved these changes

2024-12-20 12:58 UTC, IvanCeban approved these changes

2024-12-20 13:28 UTC, merged